#!/usr/bin/env bash
# AI Studio Server — main installer (called by bootstrap.sh or manually)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${AI_STUDIO_DIR:-$ROOT}"
DATA_DIR="${AI_STUDIO_DATA:-/var/lib/ai-studio}"
ENV_FILE="${DATA_DIR}/config/env"
PROFILE="${AI_STUDIO_PROFILE:-}"

log() { echo "==> $*"; }
warn() { echo "!! $*" >&2; }

require_debian() {
  if [[ ! -f /etc/debian_version ]]; then
    warn "Tested on Debian 12 / Ubuntu 22.04+. Other distros may work but are unsupported."
  fi
}

source "${ROOT}/scripts/detect-gpu.sh"

write_env() {
  mkdir -p "${DATA_DIR}/config" "${DATA_DIR}/models" "${DATA_DIR}/output" "${DATA_DIR}/logs"
  mkdir -p "${DATA_DIR}/toolkit/outputs" "${DATA_DIR}/toolkit/inbox"
  cat >"$ENV_FILE" <<EOF
# Generated by AI Studio Server install
AI_STUDIO_DATA=${DATA_DIR}
AI_STUDIO_PROFILE=${PROFILE}
COMFY_PORT=7871
ACE_PORT=7870
HUB_PORT=7880
COMFY_URL=http://127.0.0.1:7871
ACE_URL=http://127.0.0.1:7870
EOF
}

install_base_packages() {
  log "Installing base packages..."
  apt-get update -qq
  apt-get install -y -qq \
    ca-certificates curl git jq \
    python3 python3-pip python3-venv \
    ffmpeg \
    systemd
}

main() {
  require_debian

  if [[ -z "$PROFILE" ]]; then
    detect_gpu_profile
    PROFILE="${DETECTED_PROFILE:-cpu}"
  fi

  log "AI Studio Server install"
  log "Profile: $PROFILE"
  log "Data:    $DATA_DIR"

  install_base_packages
  write_env

  case "$PROFILE" in
    docker-nvidia)
      bash "${ROOT}/scripts/install-docker.sh" nvidia
      bash "${ROOT}/scripts/up-docker.sh"
      ;;
    native-rocm)
      bash "${ROOT}/scripts/install-native.sh" rocm
      bash "${ROOT}/scripts/up-native.sh"
      ;;
    cpu)
      bash "${ROOT}/scripts/install-docker.sh" cpu
      bash "${ROOT}/scripts/up-docker.sh"
      ;;
    *)
      echo "ERROR: unknown profile: $PROFILE" >&2
      exit 1
      ;;
  esac

  bash "${ROOT}/scripts/install-hub.sh"

  local host
  host="$(hostname -I 2>/dev/null | awk '{print $1}')"
  [[ -z "$host" ]] && host="127.0.0.1"

  cat <<EOF

============================================
 AI Studio Server — installed
============================================
 Profile:  $PROFILE
 Data:     $DATA_DIR
 Dashboard: http://${host}:7880/
 ComfyUI:   http://${host}:7871/
 ACE-Step:  http://${host}:7870/

 Commands (from $INSTALL_DIR):
   ./scripts/status.sh
   ./scripts/restart.sh
   ./scripts/stop.sh

 Re-run bootstrap to update:
   curl -fsSL https://raw.githubusercontent.com/lobrzut/ai-studio-server/main/bootstrap.sh | sudo bash
============================================
EOF
}

main "$@"
